# Generated by Django 2.1.7 on 2019-03-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('deck', models.ManyToManyField(related_name='player_deck', to='cards.Card')),
                ('hand', models.ManyToManyField(related_name='player_hand', to='cards.Card')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
