# Generated by Django 2.1.7 on 2019-03-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_auto_20190309_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundresult',
            old_name='points',
            new_name='score',
        ),
    ]
