# Generated by Django 2.1.7 on 2019-03-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_rounds_per_battle', models.IntegerField()),
                ('number_of_initial_cards', models.IntegerField()),
                ('number_of_cards_per_deck', models.IntegerField()),
                ('max_number_of_players', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Game Options',
                'verbose_name_plural': 'Game Options',
            },
        ),
    ]
